package org.apache.jsp.templates.custom.photogallery;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.hd.directweb.service.SimpleProperty;
import com.hd.directweb.service.TextUtils;
import com.hd.directweb.service.constants.Constants;
import com.hd.ldap.User;
import com.hd.marketing.photogallery.*;
import java.util.*;

public final class viewPhotoGallery_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.InstanceManager _jsp_instancemanager;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"errorPage.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

Map<String, Object> sessionValuesMap = (Map) session.getAttribute(Constants.SESSION_VALUES);
int strRole= TextUtils.getIntValue(sessionValuesMap.get(Constants.USER_TYPE));
SimpleProperty sp = new SimpleProperty(Constants.PROPERTY_FILE_REFERENCE);
String imagePath = sp.getProperty(PhotoGalleryConstants.PREVIEW_IMAGE_PATH);
 
User user = null;
String username = "";
if(sessionValuesMap != null && sessionValuesMap.get(Constants.LOGGED_IN_USER) != null){
	user = (User) sessionValuesMap.get(Constants.LOGGED_IN_USER);
	username = user.getUsername();
}

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<title>MRTC - Product Brand Photography Archive</title>\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"./javascript/yui/build/reset-fonts-grids/reset-fonts-grids.css\"> \r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"./javascript/yui/build/fonts/fonts-min.css?_yuiversion=2.3.1\" />\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"./javascript/yui/build/button/assets/skins/sam/button.css?_yuiversion=2.3.1\" />\r\n");
      out.write("    <SCRIPT>\r\n");
      out.write("\t\tvar xReached = 1;\r\n");
      out.write("\t\t\r\n");
      out.write("\t</SCRIPT>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"./javascript/yui/build/yahoo/yahoo.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"./javascript/yui/build/event/event.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"./javascript/yui/build/dom/dom.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"./javascript/yui/build/animation/animation.js\"></script>\r\n");
      out.write("\t<script language=\"JavaScript\" type=\"text/javascript\" src=\"./javascript/spry/xpath.js\"></script>\r\n");
      out.write("\t<script language=\"JavaScript\" type=\"text/javascript\" src=\"./javascript/spry/SpryData.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t\tvar xmlStr = \"<?xml version=\\\"1.0\\\" encoding=\\\"iso-8859-1\\\"?> \\\r\n");
      out.write("\t\t\t\t\t\t\t<photos> \\\r\n");
      out.write("\t\t\t\t\t\t\t\t<photo> \\\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<id>1</id> \\\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<dir>28</dir> \\\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<filename>sample</filename> \\\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<lastUpdated>10/01/2007</lastUpdated> \\\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<comments>comments</comments> \\\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<operatingsystem>operatingsystem</operatingsystem> \\\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<brand>brand</brand> \\\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<result>0</result> \\\r\n");
      out.write("\t\t\t\t\t\t\t\t</photo> \\\r\n");
      out.write("\t\t\t\t\t\t\t</photos>\";\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\tvar dsGallery = new Spry.Data.XMLDataSet(null, \"/photos/photo\");\r\n");
      out.write("\t\t\tvar xmlDOMDocument = Spry.Utils.stringToXMLDoc(xmlStr);\r\n");
      out.write("\t\t\tdsGallery.setDataFromDoc(xmlDOMDocument);\t\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("\tvar EDIT_PHOTO_GALLERY = 3;\r\n");
      out.write("\tvar SEND_MAIL = 5;\r\n");
      out.write("\tvar GET_OS_LIST = 6;\r\n");
      out.write("\tvar START_OVER = 7;\r\n");
      out.write("\tvar SEARCH_IMAGES = 8;\r\n");
      out.write("\t\r\n");
      out.write("\tfunction initialize()\r\n");
      out.write("\t{\r\n");
      out.write("\t\tdocument.getElementById(\"SearchResults-Container\").style.display = \"none\";\r\n");
      out.write("\t\tdocument.getElementById(\"previewContainer\").style.display = \"none\";\r\n");
      out.write("\t\tdocument.getElementById(\"RequestedPhotos-Container\").style.display = \"none\";\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tdocument.getElementById(\"EmailRequestButton\").style.display = \"none\";\r\n");
      out.write("\t\tdocument.getElementById(\"Email-CommentsContainer\").style.display = \"none\";\r\n");
      out.write("\t\t//document.getElementById(\"previewContainer\").style.position = \"absolute\";\r\n");
      out.write("\t\t");
if(strRole > Constants.ADMINISTRATOR){
      out.write("\r\n");
      out.write("\t\t\tdocument.getElementById(\"EditPhotos\").style.display = \"none\";\r\n");
      out.write("\t\t");
}
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction editPhotos(photoId)\r\n");
      out.write("\t{\r\n");
      out.write("\t\tdocument.viewGalleryForm.action='photocontroller.do?actionToBePerformed='+EDIT_PHOTO_GALLERY+'&postingID='+photoId;\r\n");
      out.write("\t\tdocument.viewGalleryForm.submit();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction deletePhotos(dir,filename,photoId)\r\n");
      out.write("\t{\r\n");
      out.write("\t\tif(confirm('Are you sure, you want to delete the Photo?'))\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tvar imgpath = '");
      out.print(imagePath);
      out.write("';\r\n");
      out.write("\t\t\tvar path = imgpath + '/' + dir +'/'+filename;\r\n");
      out.write("\t\t\tvar url = \"photocontroller.do\";\r\n");
      out.write("\t        var parameters = \"path=\"+ escape(path)+\"&photoId=\"+photoId+\"&actionToBePerformed=\"+DELETE_PHOTOS;\r\n");
      out.write("\t        if (window.XMLHttpRequest) {\r\n");
      out.write("\t            req = new XMLHttpRequest();\r\n");
      out.write("\t        } else if (window.ActiveXObject) {\r\n");
      out.write("\t            req = new ActiveXObject(\"Microsoft.XMLHTTP\");\r\n");
      out.write("\t        }\r\n");
      out.write("\t        req.open(\"POST\", url, true);\r\n");
      out.write("\t        req.setRequestHeader(\"Content-Type\", \"application/x-www-form-urlencoded;charset=UTF-8\");\r\n");
      out.write("\t        req.onreadystatechange = deleteCall;\r\n");
      out.write("\t        req.send(parameters);\r\n");
      out.write("        }else{\r\n");
      out.write("        \treturn;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction showEmailComments()\r\n");
      out.write("\t{\r\n");
      out.write("\t\tvar comments= 'Following are the photos requested by ");
      out.print(username);
      out.write(", \\n\\nPhoto ID : ';\r\n");
      out.write("\t\tvar photoId='';\r\n");
      out.write("\t\tdocument.getElementById(\"Email-CommentsContainer\").style.display = \"block\";\r\n");
      out.write("\t\t//document.getElementById(\"Email-CommentsContainer\").style.position = \"absolute\";\r\n");
      out.write("\t\tdocument.getElementById(\"previewContainer\").style.display = \"none\";\r\n");
      out.write("\t\tif(document.viewGalleryForm.requestedPhotoID.length > 1){\r\n");
      out.write("\t\t\tvar length = document.viewGalleryForm.requestedPhotoID.length;\r\n");
      out.write("\t\t\tfor(count=0;count<length;count++){\r\n");
      out.write("\t\t\t\tphotoId += document.viewGalleryForm.requestedPhotoID[count].value + ','; \r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\tphotoId = document.viewGalleryForm.requestedPhotoID.value;\r\n");
      out.write("\t\t\tif(photoId == eval('undefined'))\r\n");
      out.write("\t\t\t\tphotoId = document.viewGalleryForm.requestedPhotoID[0].value;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(photoId.indexOf(',')!=-1){\r\n");
      out.write("\t\t\tphotoId = photoId.substring(0, photoId.length-1);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tdocument.viewGalleryForm.EmailComments.value=comments + photoId;\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction cancelEmail()\r\n");
      out.write("\t{\r\n");
      out.write("\t\tdocument.getElementById(\"Email-CommentsContainer\").style.display = \"none\";\r\n");
      out.write("\t\tdocument.getElementById(\"previewContainer\").style.display = \"block\";\r\n");
      out.write("\t\t//document.getElementById(\"previewContainer\").style.position = \"absolute\";\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction sendMail()\r\n");
      out.write("\t{\r\n");
      out.write("\t\tdocument.viewGalleryForm.action='photocontroller.do?actionToBePerformed='+SEND_MAIL;\r\n");
      out.write("\t\tdocument.viewGalleryForm.submit();\r\n");
      out.write("\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\tfunction removePhotoFromRequestPhotos()\r\n");
      out.write("\t{\r\n");
      out.write("\t  \r\n");
      out.write("\t  var tbl = document.getElementById('tblRequestPhotos');\r\n");
      out.write("\t  var row = document.viewGalleryForm.requestPhotoRowId.value;\r\n");
      out.write("\t  tbl.deleteRow(row);\r\n");
      out.write("\t  document.viewGalleryForm.requestPhotoRowId.value=\"\";\r\n");
      out.write("\t  for(i=1;i<tbl.rows.length;i++) {\r\n");
      out.write("\t    var rw = tbl.rows(i);\r\n");
      out.write("\t\trw.name=\"photos\"+i;\r\n");
      out.write("\t    rw.id=\"photos\"+i;\r\n");
      out.write("\t  }\r\n");
      out.write("\t  if(document.viewGalleryForm.requestedPhotoID == null)\r\n");
      out.write("\t  \tdocument.getElementById(\"EmailRequestButton\").style.display = \"none\";\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction addToRequestPhotos(dir, filename, id)\r\n");
      out.write("\t{\r\n");
      out.write("\t\tif(document.getElementById('requestedPhotos'+id)==null)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tvar path = '");
      out.print(imagePath);
      out.write("';\r\n");
      out.write("\t\t\tvar filename = path + '/' + dir +'/'+filename;\r\n");
      out.write("\t\t\tvar tbl = document.getElementById('tblRequestPhotos');\r\n");
      out.write("\t    \tvar lastRow = tbl.rows.length;\r\n");
      out.write("\t    \titeration = lastRow;\r\n");
      out.write("\t\t\tvar row = tbl.insertRow(lastRow);\r\n");
      out.write("\t\t\trow.setAttribute('name', 'photos' + iteration);\r\n");
      out.write("\t\t\trow.setAttribute('id', 'photos' + iteration);\r\n");
      out.write("\t\t\t\trow.onclick=function() {var rownum = this.id.split('photos'); document.viewGalleryForm.requestPhotoRowId.value=rownum[1];}\r\n");
      out.write("\t          var cellRight = row.insertCell(0);\r\n");
      out.write("\t          cellRight.setAttribute('width', '160');\r\n");
      out.write("\t          var imageId = document.createElement('input');\r\n");
      out.write("\t\t\t  imageId.setAttribute('type', 'hidden');\r\n");
      out.write("\t\t\t  imageId.setAttribute('id', 'requestedPhotoID');\r\n");
      out.write("\t\t\t  imageId.setAttribute('value', id);\r\n");
      out.write("  \t\t\t  imageId.setAttribute('size', 5);\r\n");
      out.write("\t\t\t  var image = document.createElement('img');\r\n");
      out.write("\t\t\t  image.setAttribute('src', filename);\r\n");
      out.write("\t\t\t  var photoId = document.createElement('div');\r\n");
      out.write("\t\t\t  photoId.setAttribute('id', 'requestedPhotos'+id);\r\n");
      out.write("\t\t\t  photoId.innerHTML = '<b>Photo ID:</b>&nbsp;'+id;\r\n");
      out.write("\t\t\t  var line = document.createElement('hr');\r\n");
      out.write("\t\t\t  var removeLink = document.createElement('a');\r\n");
      out.write("\t\t\t  removeLink.setAttribute('href', 'javascript:removePhotoFromRequestPhotos();');\r\n");
      out.write("\t  \t\t  removeLink.appendChild(document.createTextNode(\"Remove\")); \r\n");
      out.write("\t\t\t  cellRight.appendChild(image);\r\n");
      out.write("\t\t\t  cellRight.appendChild(photoId);\r\n");
      out.write("\t\t\t  cellRight.appendChild(removeLink);\r\n");
      out.write("\t\t\t  cellRight.appendChild(line);\r\n");
      out.write("\t\t\t  cellRight.appendChild(imageId);\r\n");
      out.write("\t\t\t  document.getElementById(\"EmailRequestButton\").style.display = \"block\";\r\n");
      out.write("\t\t\t  \r\n");
      out.write("\t\t}\t  \r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\tfunction getImageCollection() {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(document.getElementById(\"req_message\")){\r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t\t \tdocument.getElementById(\"req_message\").innerHTML='&nbsp;';\r\n");
      out.write("\t \t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t        var GET_IMAGE_COLLECTION = 4;\r\n");
      out.write("\t\t\tif(document.getElementById('tblRequestPhotos').rows.length < 2){\r\n");
      out.write("\t        \tdocument.getElementById(\"EmailRequestButton\").style.display = \"none\";\r\n");
      out.write("\t        }\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t        var brandId = document.viewGalleryForm.Brand.options[document.viewGalleryForm.Brand.selectedIndex].value;\r\n");
      out.write("\t        var OS = document.viewGalleryForm.OperatingSystem.options[document.viewGalleryForm.OperatingSystem.selectedIndex].value;\r\n");
      out.write("\t        if(brandId == 0 && OS == 0)\r\n");
      out.write("\t    \t{\r\n");
      out.write("\t\t\t     alert('Please select either Brand or Operating System');\r\n");
      out.write("\t\t\t     document.viewGalleryForm.Brand.focus();\r\n");
      out.write("\t\t\t     return;\r\n");
      out.write("\t    \t} \r\n");
      out.write("\t        var url = \"photocontroller.do\";\r\n");
      out.write("\t        var parameters = \"Brand=\"+ escape(brandId)+\"&OS=\"+OS+\"&actionToBePerformed=\"+GET_IMAGE_COLLECTION;\r\n");
      out.write("\t        if (window.XMLHttpRequest) {\r\n");
      out.write("\t            req = new XMLHttpRequest();\r\n");
      out.write("\t        } else if (window.ActiveXObject) {\r\n");
      out.write("\t            req = new ActiveXObject(\"Microsoft.XMLHTTP\");\r\n");
      out.write("\t        }\r\n");
      out.write("\t        req.open(\"POST\", url, true);\r\n");
      out.write("\t        req.setRequestHeader(\"Content-Type\", \"application/x-www-form-urlencoded;charset=UTF-8\");\r\n");
      out.write("\t        req.onreadystatechange = callback;\r\n");
      out.write("\t        req.send(parameters);\r\n");
      out.write("\t    }\t\r\n");
      out.write("\t    \r\n");
      out.write("\t    function searchImages() {\r\n");
      out.write("\t    \tvar searchText = document.viewGalleryForm.searchImage.value;\r\n");
      out.write("\t    \t\r\n");
      out.write("\t    \tif(searchText == '')\r\n");
      out.write("\t    \t\treturn;\r\n");
      out.write("\t        if(document.getElementById('tblRequestPhotos').rows.length < 2){\r\n");
      out.write("\t        \tdocument.getElementById(\"EmailRequestButton\").style.display = \"none\";\r\n");
      out.write("\t        }\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t        var url = \"photocontroller.do\";\r\n");
      out.write("\t        var parameters = \"SearchText=\"+searchText+\"&actionToBePerformed=\"+SEARCH_IMAGES;\r\n");
      out.write("\t        if (window.XMLHttpRequest) {\r\n");
      out.write("\t            req = new XMLHttpRequest();\r\n");
      out.write("\t        } else if (window.ActiveXObject) {\r\n");
      out.write("\t            req = new ActiveXObject(\"Microsoft.XMLHTTP\");\r\n");
      out.write("\t        }\r\n");
      out.write("\t        req.open(\"POST\", url, true);\r\n");
      out.write("\t        req.setRequestHeader(\"Content-Type\", \"application/x-www-form-urlencoded;charset=UTF-8\");\r\n");
      out.write("\t        req.onreadystatechange = callback;\r\n");
      out.write("\t        req.send(parameters);\r\n");
      out.write("\t    }\r\n");
      out.write("\t    \r\n");
      out.write("\t    \r\n");
      out.write("\t    function callback() {\r\n");
      out.write("\t        if (req.readyState == 4) {\r\n");
      out.write("\t            if (req.status == 200) {\r\n");
      out.write("\t               \r\n");
      out.write("\t                parseMessage();\r\n");
      out.write("\t            } else {\r\n");
      out.write("\t                alert(\"No Images found for the given search criteria.\");\r\n");
      out.write("\t            }\r\n");
      out.write("\t        }\r\n");
      out.write("    \r\n");
      out.write("\t    }\r\n");
      out.write("\t    function parseMessage() \r\n");
      out.write("\t    {\r\n");
      out.write("\t    \tvar resultSet = req.responseText;\r\n");
      out.write("\t    \tvar photoId = resultSet.substring(resultSet.indexOf('<id>')+4,resultSet.indexOf('</id>'));\r\n");
      out.write("\t    \tvar dir = resultSet.substring(resultSet.indexOf('<dir>')+5,resultSet.indexOf('</dir>'));\r\n");
      out.write("\t    \tvar filename = resultSet.substring(resultSet.indexOf('<filename>')+10,resultSet.indexOf('</filename>'));\r\n");
      out.write("\t    \tvar image = dir +'/'+filename;\r\n");
      out.write("\t    \tvar lastupdated = resultSet.substring(resultSet.indexOf('<lastUpdated>')+13,resultSet.indexOf('</lastUpdated>'));\r\n");
      out.write("\t    \tvar comments = resultSet.substring(resultSet.indexOf('<comments>')+10,resultSet.indexOf('</comments>'));\r\n");
      out.write("\t    \tvar brand = resultSet.substring(resultSet.indexOf('<brand>')+7,resultSet.indexOf('</brand>'));\r\n");
      out.write("\t    \tvar os = resultSet.substring(resultSet.indexOf('<operatingsystem>')+17,resultSet.indexOf('</operatingsystem>'));\r\n");
      out.write("\t    \tvar searchResults = resultSet.substring(resultSet.indexOf('<result>')+8,resultSet.indexOf('</result>'));\r\n");
      out.write("\t    \t\r\n");
      out.write("\t    \t\r\n");
      out.write("\t\t    if(comments == 'null')\r\n");
      out.write("\t\t\t\tcomments = '';\r\n");
      out.write("\t\t\tif(lastupdated == 'null')\r\n");
      out.write("\t\t\t\tlastupdated = '';\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t    \tvar extension = '_1'+image.substring(image.lastIndexOf('.'), image.length);\r\n");
      out.write("\t    \tvar fullSizeImage = image.substring(0, image.lastIndexOf('.')) + extension;\r\n");
      out.write("\t    \t\r\n");
      out.write("\t    \tvar xmlString = \"<?xml version=\\\"1.0\\\" encoding=\\\"iso-8859-1\\\"?> \\ \" + req.responseText;\r\n");
      out.write("\t    \tdocument.getElementById(\"SearchResults-Container\").style.display = \"block\";\r\n");
      out.write("\t\t\tdocument.getElementById(\"previewContainer\").style.display = \"block\";\r\n");
      out.write("\t\t\tdocument.getElementById(\"RequestedPhotos-Container\").style.display = \"block\";\r\n");
      out.write("\t\t\tdocument.getElementById(\"imageCollection\").style.display = \"block\";\t\t\t\t\t\r\n");
      out.write("\t\t\txmlDOMDocument = Spry.Utils.stringToXMLDoc(xmlString);\r\n");
      out.write("\t\t\tdsGallery.setDataFromDoc(xmlDOMDocument);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar imgDetailedImg=\tdocument.getElementById(\"dimage\");\r\n");
      out.write("\t\t\timgDetailedImg.src = ");
      out.print(imagePath);
      out.write(" + \"/\" + fullSizeImage;\r\n");
      out.write("\t\t\tdocument.getElementById(\"lastupdated\").innerHTML='<B>LastUpdated:</B>&nbsp;'+lastupdated;\r\n");
      out.write("\t\t\tdocument.getElementById(\"comments\").innerHTML='<B>Comments:</B>&nbsp;'+comments;\r\n");
      out.write("\t\t\tdocument.getElementById(\"BrandDisplay\").innerHTML='<B>Brand Name:</B>&nbsp;'+replaceChar(brand);\r\n");
      out.write("\t\t\tdocument.getElementById(\"OSDisplay\").innerHTML='<B>Operating System:</B>&nbsp;'+replaceChar(os);\r\n");
      out.write("\t\t\tdocument.getElementById(\"SearchResults\").innerHTML='<h1>Search Results:&nbsp;'+searchResults+'&nbsp;images found</h1>';\r\n");
      out.write("\t\t\tdocument.getElementById(\"AddToRequestPhotos\").innerHTML='<a href=\\\"javascript:addToRequestPhotos(\\''+dir+'\\',\\''+filename+'\\',\\''+photoId+'\\')\\\">Add to Request Photo</a>';\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tdocument.getElementById(\"EditPhotos\").innerHTML='&nbsp;|&nbsp;<a href=\\\"javascript:editPhotos(\\''+photoId+'\\')\\\">Edit</a>';\r\n");
      out.write("\t\t\tdocument.getElementById(\"LineBreak\").innerHTML='<BR><BR>';\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t    }\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t \r\n");
      out.write("\t<!--\r\n");
      out.write("\tYAHOO.example = function() {\r\n");
      out.write("\t\tvar $D = YAHOO.util.Dom;\r\n");
      out.write("\t\tvar $E = YAHOO.util.Event;\r\n");
      out.write("\t\tvar $A = YAHOO.util.Anim;\r\n");
      out.write("\t\tvar $M = YAHOO.util.Motion;\r\n");
      out.write("\t\tvar $DD = YAHOO.util.DD;\r\n");
      out.write("\t\tvar $ = $D.get;\r\n");
      out.write("\t\tvar x = 1;\r\n");
      out.write("\t\treturn {\r\n");
      out.write("\t\t\tinit : function() {\r\n");
      out.write("\t\t\t\t$E.on(['move-left','move-right'], 'click', this.move);\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tmove : function(e) {\r\n");
      out.write("\t\t\t\t$E.stopEvent(e);\r\n");
      out.write("\t\t\t\tswitch(this.id) {\r\n");
      out.write("\t\t\t\t\tcase 'move-left':\r\n");
      out.write("\t\t\t\t\t\tif ( x === 1 ) {\r\n");
      out.write("\t\t\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tvar attributes = {\r\n");
      out.write("\t\t\t\t\t\t\tpoints : {\r\n");
      out.write("\t\t\t\t\t\t\t\tby : [680, 0]\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t};\r\n");
      out.write("\t\t\t\t\t\tx--;\r\n");
      out.write("\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\tcase 'move-right':\r\n");
      out.write("\t\t\t\t\t\tif ( x === 3 ) {\r\n");
      out.write("\t\t\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tvar attributes = {\r\n");
      out.write("\t\t\t\t\t\t\tpoints : {\r\n");
      out.write("\t\t\t\t\t\t\t\tby : [-680, 0]\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t};\r\n");
      out.write("\t\t\t\t\t\tx++;\r\n");
      out.write("\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t};\r\n");
      out.write("\t\t\t\tvar anim = new $M('themes', attributes, 0.5, YAHOO.util.Easing.easeOut);\r\n");
      out.write("\t\t\t\tanim.animate();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t};\r\n");
      out.write("\t}();\r\n");
      out.write("\tYAHOO.util.Event.onAvailable('doc',YAHOO.example.init, YAHOO.example, true);\r\n");
      out.write("\t//-->\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tfunction showPreview(lastUpdated, comments, dir, filename, photoId, os, brand)\r\n");
      out.write("\t{\r\n");
      out.write("\t\tvar path = '");
      out.print(imagePath);
      out.write("';\r\n");
      out.write("\t\tvar thumbImage = path + '/' + dir +'/'+filename;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tappendString = thumbImage;\r\n");
      out.write("\t\trExp = /.jpg/gi;\r\n");
      out.write("\t\tnewString = new String (\"_1.jpg\")\r\n");
      out.write("\t\tresults = appendString.replace(rExp, newString);\r\n");
      out.write("\t\tthumbImage = results;\r\n");
      out.write("\t\tvar imgDetailedImg=\tdocument.getElementById(\"dimage\");\r\n");
      out.write("\t\timgDetailedImg.src= thumbImage;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t\tif(lastUpdated == 'null')\r\n");
      out.write("\t\t\tlastUpdated = '';\r\n");
      out.write("\t\tif(comments == 'null')\r\n");
      out.write("\t\t\tcomments = '';\r\n");
      out.write("\t\tdocument.getElementById(\"lastupdated\").innerHTML='<B>LastUpdated:</B>&nbsp;'+lastUpdated;\r\n");
      out.write("\t\tdocument.getElementById(\"comments\").innerHTML='<B>Comments:</B>&nbsp;'+comments;\r\n");
      out.write("\t\tdocument.getElementById(\"BrandDisplay\").innerHTML='<B>Brand Name:</B>&nbsp;'+replaceChar(brand);\r\n");
      out.write("\t\tdocument.getElementById(\"OSDisplay\").innerHTML='<B>Operating System:</B>&nbsp;'+replaceChar(os);\r\n");
      out.write("\t\tdocument.getElementById(\"AddToRequestPhotos\").innerHTML='<a href=\\\"javascript:addToRequestPhotos(\\''+dir+'\\',\\''+filename+'\\',\\''+photoId+'\\')\\\">Add to Request Photo</a>';\r\n");
      out.write("\t\tdocument.getElementById(\"EditPhotos\").innerHTML='&nbsp;|&nbsp;<a href=\\\"javascript:editPhotos(\\''+photoId+'\\')\\\">Edit</a>';\r\n");
      out.write("\t\tdocument.getElementById(\"LineBreak\").innerHTML='<BR><BR>';\r\n");
      out.write("\t}\r\n");
      out.write("        \r\n");
      out.write("    function getOSListFromPhotoArchive(brandId)    \r\n");
      out.write("    {\r\n");
      out.write("        if(brandId==0)\r\n");
      out.write("    \t{\r\n");
      out.write("\t\t     return;\r\n");
      out.write("    \t} \r\n");
      out.write("    \tvar url = \"photocontroller.do\";\r\n");
      out.write("        var parameters = \"Brand=\"+ escape(brandId)+\"&actionToBePerformed=\"+GET_OS_LIST;\r\n");
      out.write("        if (window.XMLHttpRequest) {\r\n");
      out.write("            req = new XMLHttpRequest();\r\n");
      out.write("        } else if (window.ActiveXObject) {\r\n");
      out.write("            req = new ActiveXObject(\"Microsoft.XMLHTTP\");\r\n");
      out.write("        }\r\n");
      out.write("        req.open(\"POST\", url, true);\r\n");
      out.write("        req.setRequestHeader(\"Content-Type\", \"application/x-www-form-urlencoded;charset=UTF-8\");\r\n");
      out.write("        req.onreadystatechange = setResults;\r\n");
      out.write("        req.send(parameters);\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    function setResults() {\r\n");
      out.write("        if (req.readyState == 4) {\r\n");
      out.write("            if (req.status == 200) {\r\n");
      out.write("                populateOS();\r\n");
      out.write("            } else {\r\n");
      out.write("                setMessage();\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\t }\r\n");
      out.write("\tfunction setMessage()\r\n");
      out.write("    {\r\n");
      out.write("    \tvar os = document.viewGalleryForm.OperatingSystem;\r\n");
      out.write("\t\tfor (i = os.length; i>=1; i--) {\r\n");
      out.write("\t\t      os.remove(i);\r\n");
      out.write("\t    }\r\n");
      out.write("\t\talert('No Operating System found for the selected Brand');\t\r\n");
      out.write("    }\r\n");
      out.write("\t function populateOS()\r\n");
      out.write("\t {\r\n");
      out.write("\t \tvar osList = document.viewGalleryForm.OperatingSystem;\r\n");
      out.write("\t\tvar len = osList.options.length;\r\n");
      out.write("\t    for (i=len-1;i>0;i--)\r\n");
      out.write("\t\t\tosList.options[i]=null;\r\n");
      out.write("\t    var OSXMLString = req.responseXML.getElementsByTagName(\"OSCollection\")[0];\r\n");
      out.write("\t\tfor (loop = 0; loop < OSXMLString.childNodes.length; loop++) \r\n");
      out.write("\t    {\r\n");
      out.write("\t    \tvar OS = OSXMLString.childNodes[loop];\r\n");
      out.write("\t        var OSId = OS.getElementsByTagName(\"OSId\")[0];\r\n");
      out.write("\t        var OSName = OS.getElementsByTagName(\"OSName\")[0];\r\n");
      out.write("\t        var displayName = OSName.childNodes[0].nodeValue;\r\n");
      out.write("\t        displayName = replaceChar(displayName);\r\n");
      out.write("\t        \r\n");
      out.write("\t        var oOption = document.createElement(\"option\");\r\n");
      out.write("\t\t\toOption.setAttribute(\"value\", OSId.childNodes[0].nodeValue);\r\n");
      out.write("\t\t\toOption.innerHTML = displayName;\r\n");
      out.write("\t\t\tosList.appendChild(oOption);\r\n");
      out.write("\t    }\r\n");
      out.write("\t \r\n");
      out.write("\t }\r\n");
      out.write("\t function replaceChar(displayName)\r\n");
      out.write("\t {\r\n");
      out.write("\t \twhile(displayName.indexOf('~')!=-1)\r\n");
      out.write("\t \t{\r\n");
      out.write("\t \t\tdisplayName = displayName.replace('~','&');\r\n");
      out.write("\t \t}\r\n");
      out.write("\t \treturn displayName;\r\n");
      out.write("\t }\r\n");
      out.write("\t \r\n");
      out.write("\t function startOver(flag)\r\n");
      out.write("\t {\r\n");
      out.write("\t \tif(document.getElementById(\"req_message\")){\r\n");
      out.write("\t \r\n");
      out.write("\t \tdocument.getElementById(\"req_message\").innerHTML='&nbsp;';\r\n");
      out.write("\t \t}\r\n");
      out.write("\t \r\n");
      out.write("\t \tif(flag == 'StartOver'){\r\n");
      out.write("\t\t \tinitialize();\r\n");
      out.write("\t\t \tvar tbl = document.getElementById('tblRequestPhotos');\r\n");
      out.write("\t\t \tvar i=1;\r\n");
      out.write("\t\t \twhile(i<tbl.rows.length) {\r\n");
      out.write("\t\t \t\ttbl.deleteRow(i);\r\n");
      out.write("\t\t  \t}\r\n");
      out.write("\t  \t}\r\n");
      out.write("\t \t\r\n");
      out.write("\t \tdocument.viewGalleryForm.Brand.options[0].selected = true;\r\n");
      out.write("\t\tvar url = \"photocontroller.do\";\r\n");
      out.write("        var parameters = \"actionToBePerformed=\"+START_OVER;\r\n");
      out.write("        if (window.XMLHttpRequest) {\r\n");
      out.write("            req = new XMLHttpRequest();\r\n");
      out.write("        } else if (window.ActiveXObject) {\r\n");
      out.write("            req = new ActiveXObject(\"Microsoft.XMLHTTP\");\r\n");
      out.write("        }\r\n");
      out.write("        req.open(\"POST\", url, true);\r\n");
      out.write("        req.setRequestHeader(\"Content-Type\", \"application/x-www-form-urlencoded;charset=UTF-8\");\r\n");
      out.write("        req.onreadystatechange = setOSResults;\r\n");
      out.write("        req.send(parameters);\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    function setOSResults() {\r\n");
      out.write("        if (req.readyState == 4) {\r\n");
      out.write("            if (req.status == 200) {\r\n");
      out.write("                populateOS();\r\n");
      out.write("            } else {\r\n");
      out.write("                alert('Problem in resetting Operating System values, please try again later');\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\t }\r\n");
      out.write("\t \r\n");
      out.write("\t function resetBrand_OS()\r\n");
      out.write("\t {\r\n");
      out.write("\t \tstartOver('Reset');\r\n");
      out.write("\t }\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<style>\r\n");
      out.write("\t\r\n");
      out.write("\tTD.wiw-main-container {\r\n");
      out.write("BORDER-RIGHT: #ECCF82 1px solid; BORDER-TOP: #ECCF82 1px solid; PADDING-LEFT: 10px; BORDER-LEFT: #ECCF82 1px solid; WIDTH: 600px; PADDING-TOP: 8px; BORDER-BOTTOM: #ECCF82 1px solid\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("TD.wiw-search-container {\r\n");
      out.write("\tBORDER-RIGHT: #ECCF82 1px solid; \r\n");
      out.write("\tBORDER-TOP: #ECCF82 1px solid; \r\n");
      out.write("\tPADDING-LEFT: 10px; \r\n");
      out.write("\tBORDER-LEFT: #ECCF82 1px solid; \r\n");
      out.write("\tWIDTH: 750px; \r\n");
      out.write("\tPADDING-TOP: 8px; \r\n");
      out.write("\tBORDER-BOTTOM: #ECCF82 1px solid\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("      h1 {\r\n");
      out.write("\r\n");
      out.write("                font-weight: bold;\r\n");
      out.write("                margin: 0 0 1em 0;\r\n");
      out.write("                padding: .25em .5em;\r\n");
      out.write("                background-color: #F2E0B0;\r\n");
      out.write("\r\n");
      out.write("            }\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\th4\t{ font-size: 110%; margin-top:1.2em margin-bottom:1.2em; padding:1em 0 0 0; border-top:1px dashed #F2E0B0;}\r\n");
      out.write("\r\n");
      out.write("\t</style>\r\n");
      out.write("\t\r\n");
      out.write("\t<style>\r\n");
      out.write("/*Supplemental CSS for the YUI distribution*/\r\n");
      out.write("#custom-doc { width: 95%; min-width: 950px; }\r\n");
      out.write("#pagetitle {background-image: url(../../../includes/yui/build/assets/bg_hd.gif);}\r\n");
      out.write("#pagetitle h1 {background-image: url(../../../includes/yui/build/assets/title_h_bg.gif);}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\t\r\n");
      out.write("\t<style type=\"text/css\" media=\"screen, projection\">\r\n");
      out.write("\t#scrollercontainer { width: 70%; height: 115px; border: 0; padding: 10px; background-color:#fff; }\r\n");
      out.write("\t\r\n");
      out.write("\t#scroller {\r\n");
      out.write("\t\tbackground-color:#FAF5E7; \r\n");
      out.write("\t\twidth: 70%; \r\n");
      out.write("\t\theight: 118px; \r\n");
      out.write("\t\twhite-space: nowrap; \r\n");
      out.write("\t\toverflow: auto; \r\n");
      out.write("\t\tborder: 0; \r\n");
      out.write("\t\tpadding: 0; \r\n");
      out.write("\t\tSCROLLBAR-FACE-COLOR: #eccf82; \r\n");
      out.write("\t\tSCROLLBAR-HIGHLIGHT-COLOR: #ffffff; \r\n");
      out.write("\t\tSCROLLBAR-SHADOW-COLOR: #eccf82; \r\n");
      out.write("\t\tSCROLLBAR-3DLIGHT-COLOR: #FAF5E7; \r\n");
      out.write("\t\tSCROLLBAR-ARROW-COLOR:#000000;\r\n");
      out.write("\t\tSCROLLBAR-TRACK-COLOR: #FAF5E6; \r\n");
      out.write("\t\tSCROLLBAR-DARKSHADOW-COLOR: #FAF5E7;\r\n");
      out.write("\t}\r\n");
      out.write("\t#SearchResults{\r\n");
      out.write("\t\twidth:70%;\r\n");
      out.write("\t}\r\n");
      out.write("\t<!--\r\n");
      out.write("\t@import\"css/styles.css\";\r\n");
      out.write("\t#info {\r\n");
      out.write("\t\twidth:750px;\r\n");
      out.write("\t\tmargin:0 auto;\r\n");
      out.write("\t\tborder:0px solid #ECCF82;\r\n");
      out.write("\t\toverflow:hidden;\r\n");
      out.write("\t\tpadding:20px 35px;\r\n");
      out.write("\t\tposition:relative;\r\n");
      out.write("\t}\r\n");
      out.write("\t#info a {\r\n");
      out.write("\t\tbackground:#fff;\r\n");
      out.write("\t\tcolor:#333;\r\n");
      out.write("\t\tdisplay:block;\r\n");
      out.write("\t\tposition:absolute;\r\n");
      out.write("\t\ttext-decoration:none;\r\n");
      out.write("\t\ttop:50px;\r\n");
      out.write("\t\tz-index:100;\r\n");
      out.write("\t}\r\n");
      out.write("\t\t#info a#move-left {\r\n");
      out.write("\t\t\tleft:5px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#info a#move-right {\r\n");
      out.write("\t\t\tright:5px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#info .mod {\r\n");
      out.write("\t\t\toverflow:hidden;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t#themes {\r\n");
      out.write("\t\twidth:900px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.mod {\r\n");
      out.write("\tbackground:#fff;\r\n");
      out.write("\t\twidth:680px;\r\n");
      out.write("\t\toverflow:hidden;\r\n");
      out.write("\t\tmargin:0 auto;\r\n");
      out.write("\t\tposition:relative;\r\n");
      out.write("\t\tzoom:1;\r\n");
      out.write("\t}\r\n");
      out.write("\t#themes, #themes li {\r\n");
      out.write("\t\tmargin:0;\r\n");
      out.write("\t\toverflow:hidden;\r\n");
      out.write("\t\tpadding:0;\r\n");
      out.write("\t}\r\n");
      out.write("\t#themes li {\r\n");
      out.write("\t\tfloat:left;\r\n");
      out.write("\t\theight:90px;\r\n");
      out.write("\t\tmargin:0 10px 0 0;\r\n");
      out.write("\t\twidth:90px;\r\n");
      out.write("\t\tpadding:0;\r\n");
      out.write("\t}\r\n");
      out.write("\tli img {\r\n");
      out.write("\t\tborder:10px solid #fff;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tTD.wiw-main-container {\r\n");
      out.write("\t\tWIDTH: 260px; MARGIN-RIGHT: 10px; PADDING-TOP: 8px\r\n");
      out.write("\t}\r\n");
      out.write("\t-->\r\n");
      out.write("\t</style>\r\n");
      out.write("<meta http-equiv=\"content-type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("</head>\r\n");
      out.write("<body onload=\"initialize()\" bgcolor=\"#faf5e7\">\r\n");
      out.write("<form name=\"viewGalleryForm\" action=\"photocontroller.do\" method=\"post\">\r\n");
      out.write("<!-- the id on the containing div determines the page width. -->\r\n");
      out.write("<!-- #doc = 750px; #doc2 = 950px; #doc3 = 100%; #doc4 = 974px -->\r\n");
      out.write("\r\n");
      out.write("<!-- To set the Preset Template, add a class to the containing node -->\r\n");
      out.write("<!-- .yui-t1 = left 160px; .yui-t2 = left 180px; .yui-t3 = left 300px; -->\r\n");
      out.write("<!-- .yui-t4 = right 180px; .yui-t5 = right 240px; .yui-t6 = right 300px; -->\r\n");
      out.write("\r\n");
      out.write("<div>\r\n");
      out.write("\r\n");
      out.write("<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=100% height=\"100%\">\r\n");
      out.write("<tr>\r\n");
      out.write("<td width=70>&nbsp;</td>\r\n");
      out.write("\t<td colspan=2 valign=\"top\">\r\n");
      out.write("\t<DIV id=\"DeleteMessage\">&nbsp;</DIV>\r\n");
      out.write("\t");
if(request.getAttribute(PhotoGalleryConstants.MESSAGE)!=null && request.getAttribute(PhotoGalleryConstants.MESSAGE).toString().length() > 0){
      out.write("\r\n");
      out.write("    \t<table id=\"tablenobackground\">\r\n");
      out.write("    \t<tr>\r\n");
      out.write("    \t\t<td align=\"left\">\r\n");
      out.write("    \t\t    <DIV id=\"req_message\"><font color=\"red\"><b>&nbsp;&nbsp;");
      out.print(request.getAttribute(PhotoGalleryConstants.MESSAGE));
      out.write("</b></font></DIV>\r\n");
      out.write("    \t\t</td>\r\n");
      out.write("    \t</tr>\r\n");
      out.write("    \t</table>\r\n");
      out.write("    ");
}
      out.write("\r\n");
      out.write("\t<!--<h1>Product Brand Photography Archive</h1>-->\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"hd\">\r\n");
      out.write("\t");
if(request.getAttribute(PhotoGalleryConstants.BRAND_DETAILS_FROM_PHOTO_ARCHIVE)!= null)
	{
      out.write("\r\n");
      out.write("\t\t<table width=\"70%\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td class=\"wiw-search-container\">\r\n");
      out.write("\t\t\t<h1>Search Photo Gallery</h1>\r\n");
      out.write("\t\t\t<p>\r\n");
      out.write("\t\t\t\t<img src=\"../../../images/spacer.gif\" width=\"40\" height=\"1\"><b>Brand Name:</b>&nbsp;\r\n");
      out.write("\t\t\t\t<select name=\"Brand\" onchange=\"getOSListFromPhotoArchive(this.options[this.selectedIndex].value)\">\r\n");
      out.write("\t              <option value=\"0\">-------------------------Search Brand Name-------------------------</option>\r\n");
      out.write("\t\t\t\t  ");
ArrayList brandList = (ArrayList)request.getAttribute(PhotoGalleryConstants.BRAND_DETAILS_FROM_PHOTO_ARCHIVE);
	                for(int i=0;i<brandList.size();i++){
	                	BrandDO brandDO = (BrandDO) brandList.get(i);
      out.write("\r\n");
      out.write("\t                \t<option value=\"");
      out.print(brandDO.getBrandID());
      out.write('"');
      out.write('>');
      out.print(brandDO.getBrandDisplayName());
      out.write("</option>\r\n");
      out.write("\t              ");
}
      out.write("\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t");
if(strRole == Constants.ADMINISTRATOR){
      out.write("\r\n");
      out.write("\t\t\t\t\t<img src=\"../../../images/spacer.gif\" height=\"0\" width=\"30\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"searchImage\" size=\"20\"><input type=\"button\" value=\"Search\" onClick=\"searchImages()\">\r\n");
      out.write("\t\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t        <p>&nbsp;</p>\r\n");
      out.write("\t           <p><b>Operating Systems:</b>&nbsp;\r\n");
      out.write("\t           <select name=\"OperatingSystem\">\r\n");
      out.write("\t               <option  value=\"0\">--------------------Search Operating Systems--------------------</option>\r\n");
      out.write("\t               ");
ArrayList siteTermsList = (ArrayList)request.getAttribute(PhotoGalleryConstants.SITE_TERMS_FROM_PHOTO_ARCHIVE);
	                 Map OSMap = new TreeMap();
	                 for(int i=0;i<siteTermsList.size();i++){
	                  	SiteTermsDO siteTermsDO = (SiteTermsDO) siteTermsList.get(i);
	                  	OSMap.put(siteTermsDO.getAttributeDisplayName(),""+siteTermsDO.getAttributeID());
	                 }
                  	Iterator OSIterator = OSMap.keySet().iterator();
                  	while(OSIterator.hasNext()){
                  	String OSName = OSIterator.next().toString();
      out.write("\r\n");
      out.write("                   \t<option value=\"");
      out.print(OSMap.get(OSName));
      out.write('"');
      out.write('>');
      out.print(OSName);
      out.write("</option>\r\n");
      out.write("               \t\t");
}
      out.write("\r\n");
      out.write("\t\t\t   </select></p>\r\n");
      out.write("\t        <p>&nbsp;</p>\r\n");
      out.write("\t\t\t<p><input type=\"button\" value=\"Search\" id=\"button\" onclick=\"getImageCollection()\">\r\n");
      out.write("\t\t\t\t&nbsp;<input type=\"button\" value=\"Start Over\" onclick=\"startOver('StartOver')\">\r\n");
      out.write("\t\t\t\t&nbsp;<input type=\"button\" value=\"Reset\" onclick=\"resetBrand_OS()\"></p>\r\n");
      out.write("\t\t    <p>&nbsp;</p>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t<BR>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"imageCollection\" style=\"display:block;\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<p>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<DIV id=\"SearchResults-Container\">\t\r\n");
      out.write("\t\t\t\t\t<DIV id=\"SearchResults\">&nbsp;</DIV>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t <div id=\"scroller\">\r\n");
      out.write("\t\t\t\t\t\t\t<div spry:region=\"dsGallery\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img spry:repeat=\"dsGallery\" id=\"thumbImage\" style=\"border: 3px solid #f2e0b0;\"  src=\"");
      out.print(imagePath);
      out.write("/{dir}/{filename}\" onclick=\"showPreview('{lastUpdated}','{comments}','{dir}','{filename}','{id}','{operatingsystem}','{brand}')\" />\r\n");
      out.write("\t\t\t\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</DIV>\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t<p>&nbsp;</p>\t\t\r\n");
      out.write("\t\t<div id=\"yui-main\">\r\n");
      out.write("\t\t\t<div class=\"yui-b\">\r\n");
      out.write("\t\t\t\t<table id=\"previewContainer\" width=\"50%\" >\r\n");
      out.write("\t\t\t\t\t   <tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td class=\"wiw-main-container\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p><h1>Photo Preview</h1></p><p> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img id=\"dimage\" src=\"\" border=\"0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t   </tr>\r\n");
      out.write("\t\t\t\t\t   <tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"BrandDisplay\">&nbsp;</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"OSDisplay\">&nbsp;</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"comments\">&nbsp;</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"lastupdated\">&nbsp;</div>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\t\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td width=\"130\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div id=\"AddToRequestPhotos\">&nbsp;</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div id=\"EditPhotos\">&nbsp;</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div id=\"LineBreak\">&nbsp;</div>\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t</table>\t\t\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t<table id=\"Email-CommentsContainer\" width=\"75%\">\r\n");
      out.write("\t\t\t\t\t   <tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td class=\"wiw-main-container\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p><h1>Email Requested Photos</h1></p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p><textarea name=\"EmailComments\" rows=\"10\" cols=\"65\"></textarea></p>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t   </tr>\r\n");
      out.write("\t\t\t\t\t   <tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"Button\" name=\"SendMail\" value=\"Send Email\" onclick=\"sendMail()\">&nbsp;&nbsp;<input type=\"Button\" name=\"CancelMail\" value=\"Cancel\" onClick=\"javascript:cancelEmail()\">\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"yui-b\">\r\n");
      out.write("\t\t\t<table  id=\"RequestedPhotos-Container\">\r\n");
      out.write("\t\t\t\t<tr><td class=\"wiw-main-container\">\r\n");
      out.write("\t\t\t\t\t<h1>Requested Photos</h1>\r\n");
      out.write("\t\t\t\t\t\t<table id=\"tblRequestPhotos\">\r\n");
      out.write("\t\t\t\t\t  \t\t<tr><td></td></tr>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"EmailRequestButton\"><input type=\"button\" value=\"Email Request\" onclick=\"javascript:showEmailComments()\"></div>\r\n");
      out.write("\t\t\t\t\t</td>\t\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</div>\t\r\n");
      out.write("\t</div>\r\n");
}else if(request.getAttribute(PhotoGalleryConstants.MESSAGE)==null || request.getAttribute(PhotoGalleryConstants.MESSAGE).toString().length() == 0){
      out.write("\r\n");
      out.write("\t<table id=\"tablenobackground\" \">\r\n");
      out.write("\t   \t<tr>\r\n");
      out.write("\t   \t\t<td align=\"left\">\r\n");
      out.write("\t   \t\t    <DIV id=\"req_message_1\"><font color=\"red\"><b>&nbsp;&nbsp;No Images have been uploaded yet.</b></font></DIV>\r\n");
      out.write("\t   \t\t</td>\r\n");
      out.write("\t   \t</tr>\r\n");
      out.write("\t</table>\r\n");
}
      out.write("\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("</div>\r\n");
      out.write("<input type=\"hidden\" name=\"requestPhotoRowId\">\r\n");
      out.write("<input type=\"hidden\" name=\"actionToBePerformed\">\r\n");
      out.write("\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
